# Generated by Django 5.1.14 on 2026-02-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=50, verbose_name='策略名称')),
                ('start_period', models.CharField(max_length=20, verbose_name='开始期号')),
                ('end_period', models.CharField(max_length=20, verbose_name='结束期号')),
                ('total_periods', models.IntegerField(verbose_name='总期数')),
                ('starting_capital', models.FloatField(verbose_name='起始资金')),
                ('final_capital', models.FloatField(verbose_name='最终资金')),
                ('total_profit', models.FloatField(verbose_name='总收益')),
                ('roi_percentage', models.FloatField(verbose_name='ROI')),
                ('max_drawdown', models.FloatField(verbose_name='最大回撤')),
                ('bet_periods', models.IntegerField(verbose_name='投注期数')),
                ('skip_periods', models.IntegerField(verbose_name='跳过期数')),
                ('win_periods', models.IntegerField(verbose_name='盈利期数')),
                ('win_rate', models.FloatField(verbose_name='胜率')),
                ('total_invested', models.FloatField(verbose_name='总投入')),
                ('total_prizes', models.FloatField(verbose_name='总奖金')),
                ('period_results', models.JSONField(verbose_name='期次详细结果')),
                ('capital_history', models.JSONField(verbose_name='资金历史')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '回测结果',
                'verbose_name_plural': '回测结果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(max_length=20, verbose_name='更新类型')),
                ('periods_added', models.IntegerField(default=0, verbose_name='新增期数')),
                ('periods_updated', models.IntegerField(default=0, verbose_name='更新期数')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据更新日志',
                'verbose_name_plural': '数据更新日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotteryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='期号')),
                ('date', models.DateField(db_index=True, verbose_name='开奖日期')),
                ('digit1', models.IntegerField(verbose_name='第一位')),
                ('digit2', models.IntegerField(verbose_name='第二位')),
                ('digit3', models.IntegerField(verbose_name='第三位')),
                ('sum_value', models.IntegerField(verbose_name='和值')),
                ('shape', models.CharField(max_length=10, verbose_name='形态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '彩票期次',
                'verbose_name_plural': '彩票期次',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_for_period', models.CharField(db_index=True, max_length=20, verbose_name='预测的期号')),
                ('top5_digits', models.JSONField(verbose_name='Top5数字')),
                ('digit_probs', models.JSONField(verbose_name='数字概率')),
                ('confidence_score', models.FloatField(verbose_name='可信度分数')),
                ('attention_weights', models.JSONField(blank=True, null=True, verbose_name='注意力权重')),
                ('should_bet', models.BooleanField(default=False, verbose_name='建议投注')),
                ('recommended_bets', models.JSONField(blank=True, null=True, verbose_name='推荐投注组合')),
                ('bet_amount', models.IntegerField(default=0, verbose_name='建议投注金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预测时间')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='lottery.lotteryperiod', verbose_name='关联期号')),
            ],
            options={
                'verbose_name': '预测记录',
                'verbose_name_plural': '预测记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
