# Generated by Django 3.2.25 on 2026-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='bet_count',
            field=models.IntegerField(default=0, verbose_name='总注数'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='betting_combinations',
            field=models.JSONField(blank=True, null=True, verbose_name='投注组合详情'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='percentile_rank',
            field=models.FloatField(blank=True, null=True, verbose_name='置信度百分位排名'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='recommendation',
            field=models.CharField(choices=[('bet', '建议投注'), ('no_bet', '不建议投注')], default='no_bet', max_length=20, verbose_name='投注建议'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='recommendation_reason',
            field=models.TextField(blank=True, verbose_name='建议理由'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='strategy',
            field=models.CharField(default='top5', max_length=20, verbose_name='使用策略'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='total_cost',
            field=models.IntegerField(default=0, verbose_name='总成本（元）'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='bet_amount',
            field=models.IntegerField(default=0, verbose_name='建议投注金额（旧）'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='recommended_bets',
            field=models.JSONField(blank=True, null=True, verbose_name='推荐投注组合（旧）'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='should_bet',
            field=models.BooleanField(default=False, verbose_name='建议投注（旧）'),
        ),
    ]
